workflows:
  ios-native-build:
    name: iOS Native App Build (Manual Signing)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "ios_app/GlycoGuide.xcodeproj"
        XCODE_SCHEME: "GlycoGuide"
        BUNDLE_ID: "com.glycoguide.app"
        TEAM_ID: "9XVR3WAB6Y"
      groups:
        - iOS_credentials
    scripts:
      - name: Install Apple certificate
        script: |
          #!/bin/bash
          set -e
          
          KEYCHAIN_PATH="$HOME/Library/Keychains/build.keychain-db"
          KEYCHAIN_PASSWORD="codemagic"
          
          # Remove existing keychain if present
          security delete-keychain "$KEYCHAIN_PATH" 2>/dev/null || true
          
          # Create new keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Debug: Show first 50 chars of certificate data
          echo "Certificate data length: ${#IOS_DISTRIBUTION_CERTIFICATE}"
          echo "First 50 chars: ${IOS_DISTRIBUTION_CERTIFICATE:0:50}"
          
          # Clean and decode certificate - remove ALL whitespace and use macOS base64
          CLEAN_CERT=$(echo "$IOS_DISTRIBUTION_CERTIFICATE" | tr -d '\n\r\t ' )
          echo "Cleaned cert length: ${#CLEAN_CERT}"
          
          # Use printf instead of echo to avoid issues, and -D for macOS
          printf '%s' "$CLEAN_CERT" | base64 -D > /tmp/certificate.p12
          
          # Check file size
          echo "Certificate file size: $(wc -c < /tmp/certificate.p12) bytes"
          
          # Import certificate
          security import /tmp/certificate.p12 \
            -P "$IOS_CERTIFICATE_PASSWORD" \
            -A \
            -t cert \
            -f pkcs12 \
            -k "$KEYCHAIN_PATH"
          
          # Allow codesign access
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Add to keychain search list
          security list-keychains -d user -s "$KEYCHAIN_PATH" $(security list-keychains -d user | tr -d '"')
          security default-keychain -s "$KEYCHAIN_PATH"
          
          echo "Certificate installed successfully"

      - name: Install provisioning profile
        script: |
          #!/bin/bash
          set -e
          
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_DIR"
          
          # Decode profile - handle potential whitespace in base64
          echo "$IOS_PROVISIONING_PROFILE" | tr -d '\n\r\t ' | base64 -D > /tmp/profile.mobileprovision
          
          # Get profile UUID and name
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i /tmp/profile.mobileprovision))
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i /tmp/profile.mobileprovision))
          echo "Profile UUID: $PROFILE_UUID"
          echo "Profile Name: $PROFILE_NAME"
          
          # Install profile with UUID filename
          cp /tmp/profile.mobileprovision "$PROFILES_DIR/$PROFILE_UUID.mobileprovision"
          
          # Export for next step
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          
          echo "Provisioning profile installed successfully"

      - name: Build iOS App
        script: |
          #!/bin/bash
          set -e
          
          echo "Using profile: $PROFILE_NAME (UUID: $PROFILE_UUID)"
          
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath ios_app/build/GlycoGuide.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="$PROFILE_UUID" \
            archive

      - name: Export IPA
        script: |
          #!/bin/bash
          set -e
          
          # Create ExportOptions.plist with correct profile UUID
          cat > /tmp/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROFILE_UUID</string>
              </dict>
              <key>destination</key>
              <string>export</string>
          </dict>
          </plist>
          EOF
          
          echo "ExportOptions.plist created with profile UUID: $PROFILE_UUID"
          
          xcodebuild -exportArchive \
            -archivePath ios_app/build/GlycoGuide.xcarchive \
            -exportPath ios_app/build \
            -exportOptionsPlist /tmp/ExportOptions.plist

    artifacts:
      - ios_app/build/*.ipa
      - ios_app/build/*.xcarchive
      - ios_app/build/*.log

    publishing:
      email:
        recipients:
          - support@glycoguide.app
        notify:
          success: true
          failure: true
